language: R
cache: packages
sudo: required
warnings_are_errors: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
      env: R_CODECOV=true
  
r_packages:
  - devtools
  - assertthat
  - kdevine
  - rvinecopulib
  - testthat

repos:
  CRAN: http://cran.rstudio.com

after_success:
  - Rscript -e 'covr::codecov()'