dist: trusty

language: R
warnings_are_errors: true

sudo: required

apt_packages:
  - r-cran-covr
  - r-cran-kdecopula
  - r-cran-kdevine

before_install:
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo apt-get update -q
  - Rscript -e 'withCallingHandlers(install.packages("devtools", repos="http://cran.rstudio.com/"), warning=function(x) { message(x); quit(status=1, save="no") })'
  - Rscript -e 'devtools::install_github("vinecopulib/rvinecopulib", ref = "dev")'

repos:
  CRAN: http://cran.rstudio.com


after_success:
  - Rscript -e 'covr::codecov()'